server:
  port: 9090

spring:
  application:
    name: hystrix-provider-example

eureka:
  instance:
    prefer-ip-address: true

# 暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
